shell /usr/bin/bash

enable_audio_bell no
font_family HeavyData Nerd Font
confirm_os_window_close 0
scrollback_lines 2000
window_padding_width 0
confirm_close no

cursor_trail 1
cursor_trail_decay 0.1 0.2
cursor_trail_start_threshold 2

repaint_delay 4
input_delay 1

map ctrl+backspace send_text all \x17

clipboard_control write-clipboard write-primary read-clipboard read-primary

foreground       #FFFFFF
background       #16181A
cursor           #FFFFFF
