set -a terminal-features "tmux-256color:RGB"
set -g default-command "bash -i"
set -g prefix C-SPACE
set -g status-justify absolute-centre
set -g status-position top
set -g status-style "bg=default"
set -g status-interval 1

# Ctrlspace + d to detatch

bind h previous-window
bind l next-window

bind j switch-client -p
bind k switch-client -n

bind n new-window

bind m kill-window

bind r command-prompt "rename-window '%%'"

bind t command-prompt "rename-session '%%'"

set -g status-left "#S "

set -g window-status-format " #W "
set -g window-status-current-format "#[fg=green]#W#[default]"

setw -g window-status-activity-style none
setw -g window-status-separator ""

set -g status-right "#(date +'%H:%M') #(date +'%m/%d/%y')"
set-option -g update-environment "DISPLAY XAUTHORITY"
# set-hook -g attach-session 'display-message "Hook Fired: Client Attached at $(date)"'
# set-hook -g attach-session 'run-shell "/home/cameron/passwords/bash/test.sh attachessions"'
# set-hook -g session-attached 'run-shell "/home/cameron/passwords/bash/test.sh sessionattached"'
set-hook -g client-attached 'run-shell "$DOTFILES/tmuxfixTmux"'
